### ISSUE TITLE
100% recycle rate

### ISSUE THREAD

**Issue by Xanthor** [robot9706/FSSE#106]
Even though you can add items with the editor, to not have to exit and recycle new weapons to get the rare parts without the risk of failure would be a good addition. I got a weapon today, actually two that don't show up in the list and went to recycle one and failed. Went into the editor to attempt to make more of the weapon and didn't find it. Most likely came in the update I got on my tablet the day I installed the mod version. I'll also donate more as well. This is a great application.

**Comment by robot9706** [comment]
Well if you are playing with the latest (1.11.2/1.11.1) there might be some items missing from the editors.

Recycling items in the editor is not really a great idea, because the editor doesn't know the parts of the items (and if something is updaten in the game then the editor needs an update as well). However modding a 100% success rate is possible.

Thanks for your donation!

**Comment by robot9706** [comment]
[Ref](https://github.com/robot9706/FSSE/blob/gh-pages/Mods/full_recycle.patch)
