### ISSUE TITLE
Version boot check with option to terminate if true

### ISSUE THREAD

**Issue by Xanthor** [robot9706/FSSE#115]
I backup my files daily, but even doing this I can still overlook something minor that later turns into into a nightmare where I then either revert to an older save or spend hours fixing over 100 dwellers and still overlook one.
My idea is to put a version check into the loading process or make a separate program that is required to be used before loading a modded game that checks to see if there has been an update or if game has been updated and if so let the user know that they should abort loading the game until the modded version and edditor is updated.
One of my games is hevily eddited and when I went to play it I had no clue there was an update which caused over 200 dwellers, pets, and stats to be reverted which resulted in some buggy quests and a lot of game crashing. A version check would have prevented me from loading the game and allow me to have waited for an update. Just a suggestion.

**Comment by robot9706** [comment]
If the game updates by itself, I can't do anything about that because it becomes "unmodded". Matching the save and the game versions could be possible however currently I'm not really keen on doing UI mods (create a popup to ask if you want to load the game), maybe with the new modloader (it should be easier with that).

Also I'm not even sure if it's possible to check the current offical version of the game. Maybe it's possible to get the Android version from the GooglePlay page.

**Comment by Xanthor** [comment]
What if you made the editor in a way that you could use it to launch the game through it, and add features that only worked if you have the editor loaded so people got used to using it to load the game. This way it would be easier to detect a game update and warn it needs to be upgraded in order to work with the new game update.

**Comment by robot9706** [comment]
I'm not sure if that's a good idea, because then you'd also need the editor to use the mods. Also with my new modding system mods are only written once and used on every platform but the editors are different.

Maybe I could make a mod which would backup vaults with different names so the game wouldn't overwrite it, and in case the game updated you can just install the mods and move those backup vaults back to their places and it would be fine.

**Comment by Xanthor** [comment]
Didn't think of that. The past problems with game updates wasn't so much of the problem with your editor not working as it would edit everything changed back to normal specs and on more than once occasion, caused issues with missions bugging that were not completed, like saving in the middle of a mission, not back at the bunker and logging in to finding out cards/pets changed were back to normal making it impossible to finish that mission or it crash upon loading. If it can be backed up in case of an update, then data restored after editor gets updated, it would help out greatly, especially if an option to make saves automatically, then have a few options of what to restore should one be buggy.

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/137

**Comment by robot9706** [comment]
Note to self: It might be possible to get the version of the mod from the Nexus site and show a warning.
