### ISSUE TITLE
Time glitch fix causing another time glitch

### ISSUE THREAD

**Issue by MotherThruster** [robot9706/FSSE#151]
The save date in FSSE is hours forward than the save date shown in in-game vault list. 
Eg. I enter the vault at 1pm, the in-game vault list also shows the saving time at 1pm, but FSSE shows the saving time at 9pm. (This happens after I used the fix time glitch function)

Explorers gets unusually low quantity of loot. I sent 4 full stats dwellers out for 48hours, and they all return with 0 - 5 loots. (While they get 20+ in normal situation)
But the exploring time and battle log appears normally, showing correct duration of exploration and dwellers fighting creatures. It's really strange.

**Comment by MotherThruster** [comment]
https://imgur.com/a/9see6
My internal clock is at real time, but the last save time shows in FSSE is 8hours forward

**Comment by robot9706** [comment]
The time shows in GMT+8 for some reason (as it shows on the imgur pic too). So 22:08 in GMT+8 is exactly 8 hours forward from 14:08. I'll check why the time shows in random timezones.

Could you attach your vault so I could check out those broken explorers? Also if those dwellers come back to the vault and you send them back again, does that fix the problem?

https://github.com/robot9706/FSSE/issues/152

**Comment by MotherThruster** [comment]
Thanks for the quick reply. I've tried several times sending them back and it does not fix. 
Here's the two backup file, one before edit, and one after the bug appears

[backup.zip](https://github.com/robot9706/FSSE/files/1691838/backup.zip)

**Comment by robot9706** [comment]
After looking into the issue, syncing times can cause explorers to be reset, but calling them back and resending them should fix this problem (because that starts a new unmodified timer).

Anyway I modified the editor so the "time glitch" fixer thing is now a little bit more smart, so only glitched timers should be reset. Here's the new version, let me know if that did anything good.

[FSSE_dev.zip](https://github.com/robot9706/FSSE/files/1696165/FSSE_dev.zip)
