### ISSUE TITLE
Pet Boxes arent being added.

### ISSUE THREAD

**Issue by ghost** [robot9706/FSSE#153]
Game Version (win10): 1.13.52.2

Changing the amount of pet boxes seem to have no effect on the save and or in game.
Pet boxes stays at 0 even after edited to have 5 of them (for example).

**Comment by robot9706** [comment]
I tried to add some boxes and it seems it's a litle bit tricky on Win10.

So first of all there's a little bug in the editor and it doesn't see that you changed the pet boxes number, so change the pet boxes number then click on something else (for example the vault number), a "modified" tag should appear in the window title, then you can save the vault. Load the vault again in the editor to make sure the pet boxes number is correct.

Also make sure the kill the FalloutShelter app in task manager because as long as it is running the editor won't be able to save the vault, and you should also get an error message in this case, saying something like "failed to access file: ...".

This way it works for me, let me know if it works for you.

https://github.com/robot9706/FSSE/issues/154
