### ISSUE TITLE
Android Game version 1.13.9

### ISSUE THREAD

**Issue by mwsasser** [robot9706/FSSE#158]
Hi guys.  

Will version 1.6.6 still work well with the android version 1.13.9 of the game?  

I've notice the game tends to crash sometimes when it's loading missions, is this related?

**Comment by robot9706** [comment]
Since 1.13 there has been no major change in the game, so the editor should work just fine.

The crashing thing is a little bit more interesting. Recently I started seeing save files which randomly get corrupted in such a way that questing becomes buggy, the game is able to load the save, but the editor is not.

Next time your game crashes, could you attach your save file + the crash log (it's in the same folder where the saves are located, called "Fallout Shelter.log"), so maybe I could figure out your crashing issue.
