### ISSUE TITLE
Crashes on loaded save [PC] [STEAM]

### ISSUE THREAD

**Issue by buildershedd** [robot9706/FSSE#159]
Apparently, I made a huge vault using the Vault editor, now it crashes upon loading.

Vault
http://www.mediafire.com/file/729nxrqbcph55r3/Vault2.sav

**Comment by robot9706** [comment]
How did you edit this save? It contains so much broken and invalid information I just can't understand how this could happen.

Anyway, I fixed it. All the lunchboxes are gone, and I also had to remove a Theme Workshop because it was broken.

The fixed vault is attached.
[Vault2.zip](https://github.com/robot9706/FSSE/files/1910935/Vault2.zip)
