### ISSUE TITLE
Can't install app on Android?

### ISSUE THREAD

**Issue by Angkoteer** [robot9706/FSSE#162]
I know that this thread is pretty much dead, but I need help on the Android, I tried to install the apk, but it says "App not installed" after installing. I tried to look it up on google and it could be about the apk corrupted. Either this is because of it is corrupted, or maybe because of other things. I have tried installing other apks and it works, but somehow, FSSE is the only apk that wont install. Can you upload another file? Or maybe help me? Any help would be appreciated.

**Comment by robot9706** [comment]
The APK seems fine for me. If you are downloading it on your phone try using a different browser or use a download app, because sometimes for some reason the page html gets downloaded instead of the actual APK (no idea why). Or you can download the APK on a computer and copy it to your device.

**Comment by Angkoteer** [comment]
Okay, so the apk is really an apk, not a html. I have tried using puffin after chrome, both didn't work. The last thing I haven't tried is copying it from PC. Recommend me a browser / downloader please.

**Comment by robot9706** [comment]
I used Chrome and it worked fine, try ES FileExplorer, it has a downloader (when you select the APK download link on the website a dialog should pop up asking what app you'd like to use to download that file).

Also, do you have an older FSSE installed? Because I had to change the APK signature (migrated from Eclipse to Android Studio) so the old and new APKs are not compatible. Basically it won't let you update, so just download the older version and try to install the new one.

**Comment by Angkoteer** [comment]
Maybe it is because of my phone's OS, could be because my modded Fallout Shelter, maybe my other save editor. My only hope is on the PC download. Wish me luck.

**Comment by DrShpritz** [comment]
Last version is really broken. I try install another apk, and my marshmallow did it. Please repack or repair this

**Comment by robot9706** [comment]
I resigned the APK, see if that changes anything.

**Comment by DrShpritz** [comment]
YES! you did it. Thanks!

**Comment by robot9706** [comment]
I missed a checkbox to use somekind of V2 signing that's why it didn't work, sorry about that. Stuff like this happens when you change IDEs. :)
