### ISSUE TITLE
Quests bugged.

### ISSUE THREAD

**Issue by fayescarlet64** [robot9706/FSSE#52]
This only became an issue with the newest mods installed (1.3.3 version). But dwellers who are on a quest right now can't be collected, they are stuck in a loop.

**Comment by robot9706** [comment]
It could be caused by the instant wasteland quest mod, try disabling that.

**Comment by robot9706** [comment]
Tried to reproduce the problem by sending dwellers to random wasteland quests and normals quests but I could collect them without anypronlems.

**Comment by fayescarlet64** [comment]
It's the "Mask Hysteria" quest, in case it's because of a limited quest. I also only have 2 active teams, but it won't let me send another team out. I double and triple checked, and I do have a fully upgraded Overseer's Office. Demolishing it and rebuilding it to full upgrade did nothing, unfortunately. 

I disabled the instant wasteland quest mod, I'm guessing changing the 'true" option to "false" disables it.  

I deleted the dwellers who were on the quest, and that fixed things. Not sure what I did to break it, but hopefully this won't happen again. Thanks! 8D;

**Comment by robot9706** [comment]
The editor has also an option to manage mods, but yeah manually it's just changing true to false.

I'll check that quest, also if it happens again, could you attach your save here, so I could take a look and maybe firgure the problem out?

**Comment by fayescarlet64** [comment]
Can do.

**Comment by fayescarlet64** [comment]
All right, it's happened again. A daily quest caused the bug this time, and when I check the wasteland it claims there are 35 parties out. D: I've included a link to the effected Save File.

EDIT: Here is the actual file.
https://www.dropbox.com/s/m8fbcmex8xvcri0/Vault1.sav?dl=0

**Comment by robot9706** [comment]
Hm this issue is strange and I can't seem to find the cause. Somehow teams are "cloned" but in such a way which makes it inpossible to get them back to the vault. Basically multiple teams will appear with the same dwellers, so when one team is called back another copy team overwrites it. Unfortunatelly modding is limited because it is not easy to understand how the game works without proper/original tools. And this problem could be caused by something which happens inside the FoS "engine", because this behaviour is not expected.

I might however try if instead of arriving instantly, it would take 3 or 5 secs to see if that changes something.

EDIT: Which platform are you playing on?

**Comment by fayescarlet64** [comment]
I'm using the PC version. When I call them back, should I try waiting it out rather than using the Nuka Cola?

**Comment by robot9706** [comment]
I think it shouldn't matter. I tried waiting, but as soon as you close the screen and check other teams the one you just called back jumps back to the quest location.
