### ISSUE TITLE
Updating the mod pack

### ISSUE THREAD

**Issue by xMintKush** [robot9706/FSSE#68]
I was just wondering if you were going to update the mod pack so we could mod our saves on the new version of fallout shelter on the windows store with play anywhere so we can have modded saves on xbox one with it syncing from the pc to xbox

**Comment by robot9706** [comment]
The mod pack and the editor are two different things. "Modding the save" is basically editing the save. The PC editor should work with any kind of save (the platform doesn't matter).

The mod pack is a different thing, I don't have an X1 so I have no idea how the game works there. I haven't checked the windows store version but as far as I know they use special container files to keep the game files safe, so it's not possible to mod the game (but that might changed since I checked).

If you can access the *.sav files of the windows store version of the game, the PC editor should be able to edit them.

**Comment by robot9706** [comment]
https://github.com/robot9706/FSSE/issues/70

**Comment by xMintKush** [comment]
You can find it in files but when you hit load vault in the mod app it
won't show the vault

**Comment by robot9706** [comment]
You need to change the filter from *.sav to "All Files". But 1.3.7 can open win10 vaults from the file menu so there's no need to find the files.

**Comment by xMintKush** [comment]
I got it, thanks and I really like the save editor a lot
