### ISSUE TITLE
Remote Editing Issue

### ISSUE THREAD

**Issue by canoekovski** [robot9706/FSSE#74]
So I tried remote editing, everything went well until I want to save the vault but stuck on Streaming back at 6%. Using latest FSSE, mods, and Fallout Shelter itself and multiple times attempt.

**Comment by robot9706** [comment]
Well I consider the Remote editing as an obsolete feature because the PC editor can do almost everything as the Android editor. Anyway I checked it with different devices but it works stable for me, so I guess it could be some network releated issue maybe.

What you wanted to edit that you couldn't on PC?

**Comment by canoekovski** [comment]
Well ok then, I just want to add decimal number like 99.9 which is android editor can do but not for the PC.

Cheers

**Comment by robot9706** [comment]
What is that number? An item count or something? Because I tried to match numbers and their meanings so for example there are no decimal places enabled for items but they are enabled for stuff like dweller hp.

**Comment by canoekovski** [comment]
99.0 and 99.9 it was for training and crafting it has a big difference. But it's ok not a big deal though.

Cheers
